### PR TITLE
[ffi/go] Export additional APIs to go

### PR DESCRIPTION
**Pull request by traian-schiau**
blsAggregateSignature => Sign.Aggregate
blsFastAggregateVerify => Sign.FastAggregateVerify

### CODE REVIEW

**Comment by herumi** [comment]
Thank you for the patch. But please see `https://github.com/herumi/bls-eth-go-binary` if you want to use `blsFastAggregateVerify` et. al.

**Comment by traian-schiau** [comment]
Hi, I did head a look, do you think we could bring this part of bls.pathch from bls-eth-go-binary in this repo, I think is generic enough to be usable from bls-go-binary as well .

```
+// Aggregate --
+func (sig *Sign) Aggregate(sigVec []Sign) {
+	C.blsAggregateSignature(&sig.v, &sigVec[0].v, C.mclSize(len(sigVec)))
+}
+
+// FastAggregateVerify --
+func (sig *Sign) FastAggregateVerify(pubVec []PublicKey, msg []byte) bool {
+	if pubVec == nil {
+		return false
+	}
+	n := len(pubVec)
+	return C.blsFastAggregateVerify(&sig.v, &pubVec[0].v, C.mclSize(n), unsafe.Pointer(&msg[0]), C.mclSize(len(msg))) == 1
+}
+
```

**Comment by herumi** [comment]
`blsFastAggregateVerify` is available when `BLS_ETH=1` is defined, so it fails on bls-go-binary.
I wish I could remove ffi/go, but I keep it for backward compatibility.

`blsAggregateSignature` is available on bls-go-binary, but it requires binary-update, so I'm pending it.

**Comment by traian-schiau** [comment]
blsFastAggregateVerify looks to be "independent" of BLS_ETH (the nocheck one is doing nothing without BLS_ETH).

regarding the binary update,  please let me know if we can help, (I was able to make the build for linux/amd64  linux/arm64 dawin/amd64 on travis)

**Comment by herumi** [comment]
Thank you for pointing that. I've updated bls-go-binary.

**Comment by traian-schiau** [comment]
Thanks,  I think I can close this PR.

Just as a side-note,  I've also opened a PR in bls-go-binaries,  https://github.com/herumi/bls-go-binary/pull/2, please let me know what you think about that as well.

**Comment by herumi** [comment]
Okay. I'll prepare arm64 linux environments, please wait a moment.

**Pull request closed without merging**
