### PR TITLE
[go/bls] Add type conversion methods

### PR DESCRIPTION
**Pull request by traian-schiau**
Add bls public key, secret key and signature type conversion methods
to and from mcl types (G1, G2, Fr)

### CODE REVIEW

**Comment by herumi** [comment]
Thank you for the useful patch. But I appended bls/cast.go like https://github.com/herumi/bls-eth-go-binary/blob/master/bls/cast.go .
So I'm sortty that I could not merge your patch.

**Comment by traian-schiau** [comment]
Sorry, I did not see that , we are intending to use bls-go-binary. Will that cast.go make its way in this repo? If so , could we add the type assertion part from my implementation so it will support both variation of SWAP_G?

**Comment by traian-schiau** [comment]
What I'm thinking is something like:
 https://github.com/AdoAdoAdo/bls-go-binary/blob/cast_v2/bls/cast.go

**Comment by herumi** [comment]
I see, I've added https://github.com/herumi/bls-go-binary/blob/master/bls/cast.go . This repository assumes BLS_ETH is not defined, so I don't care IsSwapG.

**Comment by traian-schiau** [comment]
Thank's, I'll close this

**Pull request closed without merging**
